# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = 
name = 
handle = 
application_url = 
embedded = true

[build]
automatically_update_urls_on_dev = 
dev_store_url = 
include_config_on_deploy = 

[access_scopes]
scopes = "write_products"

[auth]
redirect_urls = []

[webhooks]
api_version = "2024-07"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/webhooks"

[pos]
embedded = false
